'use strict';
const $=selector=>document.querySelector(selector);
const titles={home:'',records:'records',settings:'settings',appearance:'appearance',buttons:'buttons',data:'backup',manual:'manualTitle',confirm:'confirmTitle'};
const t=(key,...values)=>WIBX.t(key,...values);
function translate(){document.documentElement.lang=WIBX.lang();document.querySelectorAll('[data-i18n]').forEach(el=>{const text=t(el.dataset.i18n),first=[...el.childNodes].find(node=>node.nodeType===3);if(first)first.textContent=text;else el.prepend(text);});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));$('#title').textContent=titles[current()]?t(titles[current()]):'WhyIBlockedX';$('#count').textContent=t('recordCount',rows.length);}
let settings={...WIBX.defaults},hint='black',rows=[],localDrafts={},state={stack:['home'],search:'',filter:'all',scrolls:{},drafts:{},tweetDrafts:{},openEditors:{},manual:{}},limit=100,pending=null,ready=false;
async function send(message){const result=await chrome.runtime.sendMessage(message);if(!result?.ok)throw Error(t(result?.error||'genericError'));return result;}
const current=()=>state.stack.at(-1);
function status(value){$('#status').textContent=value||'';}
function remember(){if(!ready)return;state.search=$('#search').value;state.scrolls[current()]=$('#scroll').scrollTop;state.manual=Object.fromEntries(new FormData($('#manual-form')));chrome.storage.session.set({'wibx.popup.v1':state}).catch(()=>{});}
function paint(){WIBX.prefs=settings;translate();document.documentElement.style.cssText=WIBX.style(WIBX.palette(settings.theme,hint));document.documentElement.style.colorScheme=settings.theme==='auto'&&hint==='light'?'light':'dark';document.querySelectorAll('[data-setting]').forEach(input=>{if(input.type==='checkbox')input.checked=settings[input.dataset.setting];else input.value=settings[input.dataset.setting];});}
function route(page,back=false){remember();if(back){state.stack.pop();if(!state.stack.length)state.stack=['home'];}else if(page!==current())state.stack.push(page);document.querySelectorAll('[data-page]').forEach(section=>section.hidden=section.dataset.page!==current());$('#title').textContent=titles[current()]?t(titles[current()]):'WhyIBlockedX';$('#back').hidden=state.stack.length===1;status('');if(current()==='records')render();requestAnimationFrame(()=>{$('#scroll').scrollTop=state.scrolls[current()]||0;remember();});}
$('#back').onclick=()=>{if(current()==='confirm')pending=null;route(null,true);};document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>route(button.dataset.go));
document.querySelectorAll('[data-setting]').forEach(input=>input.onchange=async()=>{input.disabled=true;try{settings=(await send({type:'setSettings',settings:{[input.dataset.setting]:input.type==='checkbox'?input.checked:input.value}})).settings;paint();status(t('saved'));}catch(error){status(error.message);paint();}finally{input.disabled=false;}});
function node(tag,cls,value){const result=document.createElement(tag);if(cls)result.className=cls;if(value!=null)result.textContent=value;return result;}
function button(label,handler){const b=node('button','',label);b.type='button';b.onclick=handler;return b;}
function render(){
 const query=state.search.trim().toLocaleLowerCase(WIBX.locale());const filtered=rows.filter(row=>(state.filter==='all'||row.action===state.filter)&&[row.handle,row.owner,row.note,row.tweetText].join(' ').toLocaleLowerCase(WIBX.locale()).includes(query));
 $('#count').textContent=t('recordCount',rows.length);$('#records').replaceChildren();$('#more').hidden=filtered.length<=limit;
 document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===state.filter)));
 if(!filtered.length){$('#records').append(node('p','empty',rows.length?t('noMatches'):t('noRecords')));return;}
 for(const row of filtered.slice(0,limit)){
  const card=node('article','record');card.dataset.id=row.id;const head=node('div','record-head');head.append(node('span','username','@'+row.handle),node('span','badge',t(row.action==='block'?'blockKind':'muteKind')+(row.endedAt?t('removedSuffix'):'')));card.append(head);
  card.append(node('div','date',new Date(row.createdAt).toLocaleDateString(WIBX.locale())+(row.owner?' · @'+row.owner:'')));
  if(row.note)card.append(node('p','',row.note));if(row.tweetText)card.append(node('p','tweet',row.tweetText));
  if(row.tweetUrl){const link=node('a','tweet-link',t('openPostPopup'));link.href=row.tweetUrl;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}
  const actions=node('div','record-actions');actions.append(button(t(localDrafts['record:'+row.id]?'backToDraft':row.note?'editReason':'addReason'),()=>edit(card,row)),button(t('delete'),()=>confirmScreen(t('deleteTitle'),t('deleteText'),t('delete'),async()=>{await send({type:'delete',id:row.id});forgetDraft(row.id);await refresh();})));card.append(actions);$('#records').append(card);
  if(state.openEditors[row.id])edit(card,row,false);
 }
}
function forgetDraft(id){delete state.drafts[id];delete state.tweetDrafts[id];delete state.openEditors[id];delete localDrafts['record:'+id];}
function edit(card,row,focus=true){
 if(card.querySelector('form'))return;
 const key='record:'+row.id,restored=localDrafts[key],form=node('form','record-editor'),input=node('textarea'),link=node('input');
 input.rows=3;input.maxLength=2000;input.setAttribute('aria-label',t('reasonFor',row.handle));input.value=restored?.note??row.note;
 link.type='text';link.inputMode='url';link.maxLength=2000;link.setAttribute('aria-label',t('tweetLink'));link.placeholder='https://x.com/…/status/…';link.value=restored?.tweetUrl??row.tweetUrl;
 state.openEditors[row.id]=true;const label=node('label','',t('tweetLink'));label.append(link);
 const hint=node('p','subtle',t(restored?'draftRestored':'shortcutHint'));let saving=false,persisted=Promise.resolve(),generation=0;
 const persist=()=>{state.drafts[row.id]=input.value;state.tweetDrafts[row.id]=link.value;localDrafts[key]={note:input.value,tweetUrl:link.value};remember();const current=++generation;hint.textContent=t('draftSaving');persisted=send({type:'draftSet',key,note:input.value,tweetUrl:link.value});persisted.then(()=>{if(current===generation)hint.textContent=t('draftSaved');},error=>status(error.message));return persisted;};
 input.oninput=link.oninput=persist;
 const actions=node('div','actions'),save=node('button','primary',t('save'));save.type='submit';
 const close=async()=>{if(saving)return;try{await persist();delete state.openEditors[row.id];form.remove();remember();render();}catch{}};
 const cancel=button(t('close'),close),remove=button(t('clearLink'),()=>{link.value='';persist();link.focus();});actions.append(save,cancel);
 form.append(input,label,remove,node('p','subtle',t('linkChangeHint')),actions,hint);form.addEventListener('wibx-close',close);
 form.onsubmit=async event=>{event.preventDefault();if(saving)return;saving=true;save.disabled=input.disabled=link.disabled=remove.disabled=cancel.disabled=true;try{await persisted;await send({type:'note',id:row.id,note:input.value,tweetUrl:link.value,draftKey:key});forgetDraft(row.id);await refresh();remember();status(t('saved'));}catch(error){status(error.message);saving=false;save.disabled=input.disabled=link.disabled=remove.disabled=cancel.disabled=false;}};
 card.append(form);if(focus)input.focus();remember();
}
async function refresh(){const data=await send({type:'list'});rows=data.records;localDrafts=data.drafts||{};$('#count').textContent=t('recordCount',rows.length);if(current()==='records')render();}
$('#search').oninput=()=>{state.search=$('#search').value;limit=100;render();remember();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;limit=100;render();remember();});$('#more').onclick=()=>{limit+=100;render();};$('#manual').onclick=()=>route('manual');
$('#manual-form').oninput=remember;$('#manual-form').onsubmit=async event=>{event.preventDefault();const record=Object.fromEntries(new FormData(event.currentTarget));if(record.tweetUrl&&!WIBX.tweetURL(record.tweetUrl.trim())){status(t('invalidTweetLink'));return;}const submit=event.currentTarget.querySelector('[type=submit]');submit.disabled=true;try{await send({type:'add',record});$('#manual-form').reset();state.manual={};await refresh();route(null,true);status(t('recordAdded'));}catch(error){status(error.message);}finally{submit.disabled=false;}};
function confirmScreen(title,text,label,action){pending=action;$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;$('#confirm-yes').textContent=label;route('confirm');}
$('#confirm-no').onclick=()=>{pending=null;route(null,true);};$('#confirm-yes').onclick=async()=>{const action=pending;if(!action)return;$('#confirm-yes').disabled=true;try{await action();pending=null;route(null,true);status(t('done'));}catch(error){status(error.message);}finally{$('#confirm-yes').disabled=false;}};
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{try{const backup=(await send({type:'export'})).backup;const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='WhyIBlockedX-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);status(t('backupDownloaded'));}catch(error){status(error.message);}});
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async()=>{const file=$('#file').files[0];$('#file').value='';if(!file)return;try{if(file.size>12*1024*1024)throw Error(t('fileTooLarge'));let backup;try{backup=JSON.parse(await file.text());}catch{throw Error(t('invalidJson'));}if(!['Neden','WhyIBlockedX'].includes(backup?.app)||![1,2,3].includes(backup.version)||!Array.isArray(backup.records))throw Error(t('invalidBackupKind'));confirmScreen(t('importBackup'),t('importText',backup.records.length),t('importAction'),async()=>{await send({type:'import',backup});await refresh();});}catch(error){status(error.message);}};
$('#clear').onclick=()=>confirmScreen(t('clearTitle'),t('clearText'),t('clearAction'),async()=>{await send({type:'clear'});state.drafts={};state.tweetDrafts={};state.openEditors={};await refresh();});
document.addEventListener('keydown',event=>{if(event.isComposing||event.keyCode===229||event.repeat)return;const form=event.target.closest('form');if(!form)return;if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)&&!event.altKey){event.preventDefault();form.requestSubmit();}else if(event.key==='Escape'){event.preventDefault();if(form.id==='manual-form')route(null,true);else form.dispatchEvent(new Event('wibx-close'));}});
$('#scroll').addEventListener('scroll',remember,{passive:true});$('#version').textContent=chrome.runtime.getManifest().version;
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes['wibx.settings.v1']||changes['wibx.xTheme.v1'])send({type:'settings'}).then(data=>{settings=data.settings;hint=data.xTheme;paint();if(current()==='records')render();}).catch(error=>status(error.message));if(changes['neden.records.v1']&&!document.querySelector('.record-editor'))refresh().catch(error=>status(error.message));});
(async()=>{const saved=(await chrome.storage.session.get('wibx.popup.v1'))['wibx.popup.v1'];if(saved){state={...state,...saved};state.stack=state.stack.filter(page=>titles[page]&&page!=='confirm');if(!state.stack.length)state.stack=['home'];}if(location.hash==='#records')state.stack=['home','records'];$('#search').value=state.search;for(const [key,value]of Object.entries(state.manual))if($('#manual-form').elements[key])$('#manual-form').elements[key].value=value;const data=await send({type:'settings'});settings=data.settings;hint=data.xTheme;paint();await refresh();ready=true;route(current());})().catch(error=>status(error.message));
